project:
  type: book
  output-dir: docs

book:
  title: After the AP Data Science Challenge (AP Statistics)
  subtitle: A Teacher Guide for a Data Science Project
  author:
  - name: Dashiell Young-Saver
    affiliation: Skew the Script
  - name: Ivonne Martinez
    affiliation: Skew the Script
  - name: Mahmoud Harding
    affiliation: Data Science 4 Everyone
  chapters:
    - index.qmd
    - intro.qmd
    - dataset.qmd
    - var.qmd
    - tips.qmd
    - commands.qmd
    - references.qmd
    - partners.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

date: today

number-sections: false

editor: visual